export const adjectives = [
    "Kör",
    "Yaşlı",
    "Ölmüş",
    "Konuşmadığın",
    "Bunak",
    "Komadaki",
    "Baygın",
    "Hasta",
    "Şaşı",
    "Nefes darlığı çeken",
    "Tanga giyen",
    "Kokan",
    "Konyalı",
    "Kanser",
    "Sakat",
    "Felçli",
    "Engelli",
    "Irz düşmanı",
    "Hıyar",
    "Kütük",
    "Köpek",
    "Piç",
    "Kaltak",
    "Boklu",
    "Şerefsiz",
]