export const predicates = {
  orientation: [
    "kafamı sokarım",
    "sinek 2'yi kılıçlama atarım",
    "salıncak kurarım",
    "hafifçe fısıldarım",
    "haykırırım",
    "ağaç dikerim",
    "kardan adam diker, havucunu yerim",
    "vidanjör hortumu atarım",
    "kuyu açarım",
    "format atarım",
    "okey masası kurar dördüncü ararım",
    "hıçkırırım",
    "seçim sandığı kurarım",
    "internet explorer kurarım",
    "bayrak dikerim",
    "yoğurt döküp sikerim",
    "beton dökerim",
    "kızgın demir sokarım",
    "kayyum atarım",
    "hapşururum",
    "kiremit döşerim",
    "vapur yanaştırırım",
    "bedava servis kaldırırım",
    "geçmiş olsun çiçeği gönderirim",
    "rektör atarım",
    "noter açarım",
    "tarıma elverişli arazi izni veririm",
    "öyle bir sokarım ki myspace parolasını hatırlar",
    "kızgın demiri ters sokarım, tutup çıkaramaz",
    "kaymakam atarım",
    "kaymakam atanırım",
    "tüp sokarım",
    "website kurarım",
    "kazık sokarım",
    "mıhlarım",
    "balta saplarım",
    "kazık çakarım",
    "tornavida saplarım",
    "balgam atarım",
    "sırtlan gibi çökerim",
    "kelebek saplarım",
    "roket fırlatırım",
    "çekirdek çitlerim",
    "duvar örerim",
    "beton dökerim",
    "çivi çakarım",
    "tırpan atarım",
    "testere çekerim",
    "kargaburnu sokarım",
    "kerpetenle çekerim",
    "hidrolik pres basarım",
    "elektrik veririm",
    "zımpara çekerim",
    "boya fırçası sallarım",
    "sıva yaparım",
    "kalas dikerim",
    "kazma saplarım",
    "kürek saplarım",
    "bomba atarım",
    "mayın döşerim",
    "tuzak kurarım",
    "kötek çekerim",
    "şaplak atarım",
    "yumruk atarım",
    "kafa atarım",
    "parmak atarım",
    "dil atarım",
    "tükürürüm",
    "osururum",
    "sıçarım",
    "işerim",
    "takla attırırım",
    "fitil atarım",
    "kök söktürürüm",
    "gezegen çarptırırım",
    "yok ederim",
    "diriltirim",
    "lanet okurum",
    "büyü yaparım",
    "cin çarptırırım",
    "şeytan gönderirim",
    "çarşamba pazarı kurarım",
  ],
  status: [
    "boza pişiririm",
    "havuç rendelerim",
    "halay çekerim",
    "vergi beyannamesi formu doldururum",
    "balık tutarım",
    "hilti çalıştırırım",
    "konser veririm",
    "miting yaparım",
    "at yarışı düzenlerim",
    "bakanlar kurulunu toplarım",
    "davul çalarım",
    "2. derece yanık oluştururum",
    "balmumu heykel müzesi açarım",
    "yavaşça gezdiririm",
    "zeytin dalı oynarım",
    "otopark açarım",
    "tek kale maç yaparım",
    "fırfır yaparım",
    "çiğ köfte yoğururum",
    "türkü söyleye söyleye gezerim",
    "anonim şirket açarım",
    "dolar bozdururum",
    "hayır çeşmesi açarım",
    "izinsiz gösteri düzenlerim",
    "bitcoin alışverişi yaparım",
    "piknik yaparım",
    "tavla oynarım",
    "kırbaç şaklatırım",
    "kara delik açarım",
    "evren yaratırım",
    "düdük çalarım",
    "zil çalarım",
    "korna çalarım",
    "yangın çıkarırım",
    "sel basarım",
    "çığ düşürürüm",
    "deprem yaratırım",
    "volkan patlatırım",
    "kasırga estiririm",
    "tsunami yaratırım",
    "güneş batırırım",
    "ay doğururum",
    "yıldız kaydırırım",
    "demir doğrama atölyesi açarım",
    "tank sürer, topunu anasının amına ateşlerim",
    "50 sezonluk dizi çekerim",
    "at kişnetirim",
    "saman altından su yürütürüm",
  ],
};
