export const subjects = [
    "ananın",
    "babanın",
    "dayının",
    "teyzenin",
    "halanın",
    "amcanın",
    "dedenin",
    "ninenin",
    "ebenin",
    "bacının",
    "ablanın",
    "validenin",
    "ilkokul öğretmeninin",
    "lise öğretmeninin",
    "üniversite öğretim üyenin",
    "kuzeninin",
    "bacının",
    "ablanın",
    "kardeşinin",
];